models/joueur.py
class Joueur:
    def __init__(self, nom):
        self.nom = nom  # Attribut pour le nom du joueur
    
    def __str__(self):
        return f"Joueur : {self.nom}"

app.py
from flask import Flask
from views import views


app = Flask(__name__)

#Enregistrement du Blueprint 
app.register_blueprint(views ,url_prefix='/')

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import render_template, request, redirect, url_for
from flask import Blueprint
from models.joueur import Joueur
import json

views = Blueprint('views', __name__, template_folder='../templates')


nb_player =""

# Route principale pour la page d'accueil
@views.route('/')
def index():
    return render_template('index.html', nb_player=0)  # Passer nb_player avec une valeur initiale



# Route pour la configuration des joueurs
@views.route('/listeJoueur', methods=['POST'])
def config_joueur():

    global nb_player
    # Récupération des données du formulaire
    nb_player = request.form.get('quantity', "").strip()  
    rule = request.form.get('rule', "").strip()           

    # Vérification si les données existent
    if not nb_player or not rule:
        # Si une des valeurs est absente, retour à la page d'accueil
        return render_template('index.html', error="Veuillez remplir tous les champs.", nb_player=0, rule="")

    # Convertir nb_player en entier et gérer les erreurs
    try:
        nb_player = int(nb_player)
        if nb_player <= 1:  # S'assurer que nb_player est un entier superieur a 1 
            raise ValueError("Le nombre de joueurs doit être supérieur à 1.")
    except ValueError as e:
        return render_template('index.html', error=str(e), nb_player=0, rule=rule)

    # Si tout est valide, afficher la page listeJoueur.html
    return render_template('listeJoueur.html', nb_player=nb_player, rule=rule)



# Route pour débuter une partie de poker 
@views.route('/listeJoueur/jeu',methods=['GET', 'POST'])
def jeu():




    global nb_player

    # Charger le fichier JSON contenant les éléments du backlog
    with open('backlog.json', 'r') as f:
        data = json.load(f)

    backlog = data['backlog']
    
    # Récupérer le numéro de la question à partir de l'URL, sinon commencer à 1
    numero = 1

    # Chercher la question correspondant au numéro
    question = next((q for q in backlog if q["numero"] == numero), None)

    # Si la question existe, récupérer l'index pour savoir s'il y a une question suivante
    if question:
        # Nombre total de questions
        nb_items = len(backlog)
        next_question = numero + 1 if numero < nb_items else None
    else:
        question = {"numero": "Erreur", "titre": "Question non trouvée"}
        next_question = None






    nb_player = int(nb_player)
    joueurs = []
    if request.method == 'POST':
        for i in range(nb_player):
            # Récupérer le nom du joueur depuis le formulaire
            nom_joueur = request.form[f'player{i}']
            joueur = Joueur(nom_joueur)  # Créer une instance de Joueur
            joueurs.append(joueur)  # Ajouter à la liste des joueurs
        

    cartes = ["cartes_0.svg", "cartes_1.svg", "cartes_2.svg", "cartes_3.svg", 
              "cartes_5.svg", "cartes_8.svg", "cartes_13.svg", "cartes_20.svg", 
              "cartes_40.svg", "cartes_100.svg", "cartes_cafe.svg", "cartes_interro.svg"] 
    return render_template('jeu.html', cartes=cartes , nb_player=nb_player , joueurs=joueurs , question=question, numero=numero, next_question=next_question)

templates/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Accueil</title>
</head>
<body>
     <!-- Formulaire avec méthode POST -->
     <form action="{{ url_for('views.config_joueur') }}" method="POST">
            <div class="formulaire">
                    <div class="champ1">
                        <!-- Champ numérique pour l'entrée d'un nombre -->
                        <label for="quantity" class="nb_player">Nombre de Joueur</label>
                        <input type="number" id="quantity" name="quantity" value="0" min="0" max="100" step="1" class="val_nb_player" required>
                        
                        {% for i in range(nb_player | int) %}
                        <div>
                            <label for="player{{ i }}" class="nb_player">Joueur {{ i + 1 }}</label>
                            <input type="text" id="player{{ i }}" name="player{{ i }}">
                        </div>
                        {% endfor %}
                    </div>
                    
                    <div class="champ2">
                        <!-- Liste déroulante pour choisir une option -->
                        <label for="rule" class="rules">Règles de Planning Poker</label>
                        <select id="rule" name="rule" required>
                            <optgroup label="Sélectionner une règle">
                                <option value="moyenne">Moyenne</option>
                                <option value="médiane">Médiane</option>
                                <option value="majorite_absolue">Majorité absolue</option>
                                <option value="majorite_relative">Majorité relative</option>
                            </optgroup>
                        </select>
                    </div>

                    <!-- Bouton pour soumettre le formulaire -->
                    <div class="champ3">
                        <input type="submit" value="Faire une partie">
                    </div>
                    {% if error %}
                    <p style="color: red; text-decoration: underline;" class="erreur_index">{{ error }}</p>
                    {% endif %}

            </div>
        </form>
</body>
</html>

templates/jeu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Lien vers le fichier CSS externe -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jeu.css') }}">
</head>
<body>
    <div class="card-container">

        <div>
            <!-- Affichage de la question et de son titre -->
            <p>Question {{ question.numero }} : {{ question.titre }}</p>
    
            <!-- Formulaire pour passer à la question suivante -->
            {% if next_question %}
                <a href="{{ url_for('views.jeu') }}?numero={{ next_question }}">
                    <button>Suivant</button>
                </a>
            {% else %}
                <p>Fin du backlog</p>
            {% endif %}
        </div>

        <ul class="listeJ">
            {% for i in range(nb_player) %}
                <li class="player">
                    <img src="{{ url_for('static', filename='images/joueur.png') }}" alt="Image Joueur {{ i + 1 }}" class="player-image">
                    <p>{{ joueurs[i].nom }}</p>
                </li>
            {% endfor %}
        </ul>
        
        {% for carte in cartes %}
            <div><img src="{{ url_for('static', filename='images/' + carte) }}" alt="Carte {{ loop.index }}  " class="cards"></div>
        {% endfor %}

    </div>
</body>
</html>

templates/listeJoueur.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Inclusion de 2 fichiers CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listeJoueur.css') }}">
    <title>Accueil</title>
</head>
<body>
    <!-- Formulaire avec méthode POST -->
    <form action="{{ url_for('views.jeu') }}" method="POST">
        <div class="formulaire">
            <div class="champ1">
                <!-- Dynamically generated player inputs based on nb_player -->
                {% for i in range(nb_player | int) %}
                    <div>
                        <label for="player{{ i }}" class="nb_player">Joueur {{ i + 1 }}</label>
                        <input type="text" id="player{{ i }}" name="player{{ i }}" class="player-input" required>
                    </div>
                {% endfor %}
            </div>

            <!-- Bouton pour soumettre le formulaire -->
            <div class="champ3">
                <input type="submit" value="Jouer" class="submit-button">
            </div>
        </div>
    </form>
</body>
</html>